#!/bin/sh
echo "                                                          "
echo " ...Skin Blue-Line-OCT-4HDF by stein17 successful installed.  "
echo "                                                          "
exit 0


