#!/bin/sh
echo "                                                           "
echo " Skin Blue-Line-OCT-4HDF by stein17 is now being removed...    "
echo "                                                           "
