#!/bin/sh
if [ -f /AX_Blue_FHD_4HDF/skin.xml ]; then
  rm -rf /usr/share/enigma2/AX_Blue_FHD_4HDF/
  mv /tmp/AX_Blue_FHD_4HDF /usr/share/enigma2/
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AXBlueFHD/
  mv /tmp/AXBlueFHD /Extensions/Plugins/python/enigma2/lib/usr/
fi
echo "                                                          "
echo " ..AX_Blue_FHD_4HDF Skin  by stein17 successful installed. "
echo "                                                          "
exit 0

