#!/bin/sh
echo "                                                                            "
echo "                         ***** WARNING ****                                 "
echo "AX_Blue_FHD_4HDF skin requires a minimal dual core.                         "
echo "AX_Blue_FHD_4HDF skin is NOT guaranteed to work on slower or older receivers.    "
echo "                                                                            "
echo "                                                                            "
echo "                                                                            "
echo "Check if a previous version of the AX_Blue_FHD_4HDF skin is installed"
if [ -f /usr/share/enigma2/AX_Blue_FHD_4HDF/skin.xml ]; then
    cp -R /usr/share/enigma2/AX_Blue_FHD_4HDF/ /tmp
    rm -rf /usr/share/enigma2/AX_Blue_FHD_4HDFF
    rm -rf /usr/lib/enigma2/python/Components/Converter/AXBlue*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/AXBlue*
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AXBlueFHD*
    echo "                                                   "
    echo "Previous AX_Blue_FHD_4HDF skin installation        "
    echo "    was found and removed successfully!            "
    echo "                                                   "
fi
echo "                                                       "
echo "AX_Blue_FHD_4HDF skin is now being installed...        "
echo "                                                       "
exit 0

