#!/bin/sh
echo "                                                           "
echo " AX_Blue_FHD_4HDF by stein17 is now being removed...    "
echo "                                                           "
