#!/bin/sh
opkg install enigma2-plugin-systemplugins-weathercomponenthandler
opkg install --force-reinstall minilocale
echo " ...Multibox Skin Full HD by stein17 successful installed.  "
echo "                                                          "
exit 0
