#!/bin/sh
rm -rf /usr/share/enigma2/Multibox
rm -rf /usr/lib/enigma2/python/Components/Converter/AMB*
rm -rf /usr/lib/enigma2/python/Components/Renderer/AMB*
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MultiboxFHD*
echo "                                                                 "
echo "Multibox skin was successfully removed from your receiver"
echo "                                                                 "
echo "The GUI of your receiver is now rebooting....                    "
exit 0                                                       "
